//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class locations
    {
        public locations()
        {
            this.farmer_location = new HashSet<farmer_location>();
            this.location_plant = new HashSet<location_plant>();
            this.plants = new HashSet<plants>();
            this.sales = new HashSet<sales>();
        }
    
        public int id { get; set; }
        public string district { get; set; }
        public string county { get; set; }
        public string province { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<farmer_location> farmer_location { get; set; }
        public virtual ICollection<location_plant> location_plant { get; set; }
        public virtual ICollection<plants> plants { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
