//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class plants
    {
        public plants()
        {
            this.location_plant = new HashSet<location_plant>();
            this.sales = new HashSet<sales>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual customers customers { get; set; }
        public virtual ICollection<location_plant> location_plant { get; set; }
        public virtual locations locations { get; set; }
        public virtual plant_brands plant_brands { get; set; }
        public virtual ICollection<sales> sales { get; set; }
        public virtual plants plants1 { get; set; }
        public virtual plants plants2 { get; set; }
    }
}
